### ISSUE TITLE
Deprecated string regex replace fix

### ISSUE THREAD

**Issue by cyrillustan** [meyer-lab/tensordata#1]
Hey @murphymadeleine21, this is a new repo dedicated to saving all tensor related data. In recent runs of importing Alter data, lines 54 and 27 have issues shown below:

```
/Users/cyrillus/Library/Caches/pypoetry/virtualenvs/tensordata-1GWWSKwC-py3.9/lib/python3.9/site-packages/tensordata/alter.py:54: FutureWarning: The default value of regex will change from True to False in a future version.
  df["variable"] = df["variable"].str.replace("IgG.", "")
/Users/cyrillus/Library/Caches/pypoetry/virtualenvs/tensordata-1GWWSKwC-py3.9/lib/python3.9/site-packages/tensordata/alter.py:27: FutureWarning: The default value of regex will change from True to False in a future version.
  df["variable"] = df["variable"].str.replace("." + antigen, "")
```

I think [this post](https://stackoverflow.com/questions/66603854/futurewarning-the-default-value-of-regex-will-change-from-true-to-false-in-a-fu) can be related to this issue. Since you wrote this import function before, can you help me by fixing this? Thank you!

**Comment by murphymadeleine21** [comment]
Oh yes, all we need to do is add `regex=True` in the function call `str.replace()`
